### ISSUE TITLE
Sign up for February meeting (2/24) here!

### ISSUE THREAD

**Issue by mjgiarlo** [ComputerAnonymousSeattle/computer#15]
See here for details: http://computeranonymous.org/us_seattle.html

(6pm-9pm, The Pine Box, Pike/Pine.)

**Comment by bwreilly** [comment]
I'm in, looking forward to it

**Comment by mjgiarlo** [comment]
:metal: Great, see you there!

**Comment by bwreilly** [comment]
Having some trouble finding the table.
