### ISSUE TITLE
Sign up for March meeting (3/31) here!

### ISSUE THREAD

**Issue by mjgiarlo** [ComputerAnonymousSeattle/computer#16]
See here for details: http://computeranonymous.org/us_seattle.html

(6pm-9pm, ClipCard offices (Suite 1102), Denny Triangle.)

**Comment by foundatron** [comment]
For those coming to Mar 31st Meeting... the doors for building actually close at 6pm. I'll be waiting down by the door for about 10 minutes after 6 to let in people. After that, there will be a sign that you will be able to see with my phone number. Just call that number and I'll run down.... or Google plus hangout-message-text-sms me﻿
