### ISSUE TITLE
Sign up for May meeting (5/22) here!

### ISSUE THREAD

**Issue by mjgiarlo** [ComputerAnonymousSeattle/computer#18]
See here for details: http://computeranonymous.org/us_seattle.html#meetings

(6pm-9pm, Twilight Exit, Central District.)

**Comment by Thesoro** [comment]
I want to come but I've got M's tickets--I'll have to try for the June one!

**Comment by mjgiarlo** [comment]
No worries, @Thesoro! We'll see you in June, then.

**Comment by mjgiarlo** [comment]
See here, @Thesoro: #19
