### ISSUE TITLE
Select a location for first meet-up

### ISSUE THREAD

**Issue by mjgiarlo** [ComputerAnonymousSeattle/computer#2]

**Comment by whatdog** [comment]
Pick a neighborhood. Some suggestions.
Spinnaker - Columbia City, rotating food trucks.
Pub at Third Place - Ravenna, Greek food.
Outlander - Fremont. Good tables, low noise, nanobrews.

**Comment by mjgiarlo** [comment]
Yo @whatdog: we also have some suggestions here: http://computeranonymous.org/us_seattle.html

Outlander sounds rad.

**Comment by whatdog** [comment]
Yeah. Still figuring out this github thing. So what's up with the github issues? More specifically, what types of responses are expected and are comments the right place for these responses?  As for editing the github CA page, still haven't gotten around to figuring out the separate ssh keygen config for multiple github accounts on the same box.

**Comment by mjgiarlo** [comment]
@whatdog I think we can use these issues to plan events, so every "task" is an issue, and we can discuss details within each issue like we've started here.

To edit our page at computeranonymous.org, you can do that right on the web:

https://github.com/ComputerAnonymousSeattle/computer/edit/gh-pages/us_seattle.html

And then when you're satisfied with your edits, you can issue a pull request back to the computeranonymous folks here:

https://github.com/ComputerAnonymousSeattle/computer/compare

And when they merge it, GitHub will rebuild the pages and your edits will be live!  (Btw, there are buttons for both of the above functions, but it was easier for me to give the links than to explain what the buttons are, where they are, etc.)

**Comment by mjgiarlo** [comment]
I'd be interested in hearing whether this works for you both, @whatdog and @diplomatica.

**Comment by mjgiarlo** [comment]
Also re: the location, maybe we could find a date/time that works first, see who can make it, and pick a place based on where the plurality of folks seem to be based.

**Comment by whatdog** [comment]
Fine. @mjgiarlo you mean, I'm supposed to actually look at that source code page for CA Seattle and click that edit tab in the corner? Clicky click click. Between @mjgiarlo, @diplomatica and me, we have the North - South corridor fairly evenly spread

**Comment by diplomatica** [comment]
Dates first sounds good. I might come in paint and plaster splattered
clothes if we meet in November. Home reno begins! Should we do the Doodle
dance or propose some dates via this thread?

**Comment by mjgiarlo** [comment]
@whatdog Yup, view the source then click the edit button!  And we do have a good spread, don't we?

@diplomatica Either is OK.  First one to suggest dates here or draft a Doodle poll can set a precedent for the rest of us?

**Comment by whatdog** [comment]
No strong opinions on Doodle, but this thread works for me since I'm already here. 
Tues. nights are generally out. Nov 7-11th generally out -- got to fly back for my dad's funeral, the date has not been set yet. Other than that Nov. is pretty open. Weekends are pretty good except for Saturday before noon.

**Comment by mjgiarlo** [comment]
Nov 3-7 are bad for me because I'll be in Austin for DLF Fall Forum.  How does the week of Halloween look?

Weekends could work, too, unless we felt strongly that Computer was too work-y for our family/friends/gardening/dogwalking/videogame time.

**Comment by whatdog** [comment]
So a tentative second half of November is shaping up. @mjgiarlo yeah. love our spread. @diplomatica we're invading your kitchen renovation and expecting a 6-burner Wolf or Viking -- ok maybe not.

**Comment by mjgiarlo** [comment]
Yo, yo, I'm asking about the last week of Oct.  If not that week, then latter half of Nov could work (though I am also traveling Nov 20-22).

**Comment by whatdog** [comment]
Oh yeah, the last week of Oct works for me. Also, I really like Outlander and they do have food, I vaguely recall their food being better than average pub fare.

**Comment by whatdog** [comment]
@mjgiarlo Thanks for the edit and pull links, I hate buttons, I hate gui's and I'm going to listen to the Ramone's, "I'm against it."

**Comment by diplomatica** [comment]
Yeah - 10/23 or 10/24 work in the evenings. So does 10/29 or later evening
of 10/30. Weekends - 10/26, most weekends in November could probably be
doable (minus first weekend and T-giving).
e

**Comment by mjgiarlo** [comment]
Of those, @diplomatica, I lean towards Thurs the 24th and Tues the 29th (if @whatdog could make that Tues).  What say you, @whatdog :question:

**Comment by mjgiarlo** [comment]
(Btw, for others who may be viewing this, for future meetings when we have a better idea of WTF we're doing, Doodles would make sense so we could be more inclusive.)

**Comment by whatdog** [comment]
@mjgiarlo @diplomatica Let's go with 10/24 at Outlander? If that's out, I can skip tai chi on 10/29. Yeah, sure with the Doodle thing for future time discussions.

**Comment by diplomatica** [comment]
@mjgiarlo @whatdog 10/24 sounds good. What time? 6:00pm? Later?

**Comment by whatdog** [comment]
Sweet. 10/24, 6pm Outlander.

**Comment by whatdog** [comment]
@mjgiarlo @diplomatica Edited the page, but haven't issued the pull request.

**Comment by mjgiarlo** [comment]
Looks like your changes are live, @whatdog!  Marking this as closed. :+1:
