### ISSUE TITLE
Sign up for July meeting (7/23) here!

### ISSUE THREAD

**Issue by mjgiarlo** [ComputerAnonymousSeattle/computer#20]
See here for details: http://computeranonymous.org/us_seattle.html#meetings

(6pm-9pm, Chuck's Hop Shop, Central District (not the Greenwood location!).)

**Comment by JaimeLynSchatz** [comment]
I swear I'm going to make it to one of these soon! I'm going to try hard for this one! :smile: Admitting you have a problem is the first step, right? :laughing:

**Comment by mjgiarlo** [comment]
Ha, @jaimelynschatz! No worries, and no pressure -- we're not going anywhere. :)

**Comment by fhocutt** [comment]
Hey, awesome! I can make this one.

**Comment by JaimeLynSchatz** [comment]
:thumbsup: :thumbsup: !! :)

**Comment by mjgiarlo** [comment]
:clap: C'mon by, y'all!

**Comment by mjgiarlo** [comment]
Computerers: the usual planners (me, @diplomatica﻿, @whatdog﻿) are all booked up for August. If others want to plan a meeting, get in touch and I can help out!

**Comment by mjgiarlo** [comment]
And we're back: #21
