### ISSUE TITLE
Help plan a get-together!

### ISSUE THREAD

**Issue by mjgiarlo** [ComputerAnonymousSeattle/computer#24]
Would any folks like to help plan future events? I'm low on cycles to set 'em up (but can still find time to attend).

**Comment by JaimeLynSchatz** [comment]
I'm a little low on cycles, too, but maybe if I plan an event I might actually make it out there! :laughing: Would anyone mind if a newbie to the group organized one?

**Comment by mjgiarlo** [comment]
I wouldn't mind at all, @JaimeLynSchatz!

Here's the guide:

https://github.com/ComputerAnonymousSeattle/computer/wiki/Planning-an-event

If there's anything I can help with, drop me a line here or via email (see my GitHub profile).  Cool?

**Comment by JaimeLynSchatz** [comment]
I've been so swamped - I started looking at dates and venues and then started drowning at work. I'm looking again, though.

**Comment by mjgiarlo** [comment]
No worries, @JaimeLynSchatz. Thanks for looking into this.
