### ISSUE TITLE
June 2015 get together

### ISSUE THREAD

**Issue by whatdog** [ComputerAnonymousSeattle/computer#25]
Any thoughts on dates and locations for a June meetup?

**Comment by flowerhack** [comment]
Next week I am out of town, but I'm free pretty much evening the week of the 22nd!

Maybe, arbitrarily, the evening of the 24th?  Someone else should recommend a location, though, I don't really know many places in Seattle yet :)

**Comment by mjgiarlo** [comment]
I'm flexible w/r/t everything. Thanks for pulling this together, @whatdog!

**Comment by whatdog** [comment]
Thursday the 25th works better for me. Dave Tolmie suggested Toronado again, since he is partial to areas a bit further north. I like Toronado's beer and food, so I could go with that unless I hear otherwise. Let me know if the 25th would work for people.

**Comment by dtolmie** [comment]
Partial to places up north, but more importantly, addicted to their corned
beef hash!

Thursday the 25th works for me.

-d

**Comment by mjgiarlo** [comment]
Totally cool!

**Comment by whatdog** [comment]
K. Lemme figure out how to change my default git user or somesuch, so I can edit this thing.

**Comment by mjgiarlo** [comment]
:OK: Ping me if it gets annoying.

**Comment by mjgiarlo** [comment]
#26 is created, so closing this issue.
