### ISSUE TITLE
Sign up for October meeting (10/5) here!

### ISSUE THREAD

**Issue by whatdog** [ComputerAnonymousSeattle/computer#28]
See here for details: http://computeranonymous.org/us_seattle.html#meetings
(6pm-9pm, [Reuben's Brews on 14th Ave NW](https://www.google.com/maps/place/Reuben's+Brews/@47.6654308,-122.3730504,15z/data=!4m2!3m1!1s0x0:0x90d7c5a5e5dcf1ab), Ballard.)

**Comment by mjgiarlo** [comment]
:+1:

**Comment by dtolmie** [comment]
🍻

BTW, the main page still shows Outlander as the location.

**Comment by mjgiarlo** [comment]
Yeah, that page can take hours to update. :/

**Comment by mjgiarlo** [comment]
https://github.com/ComputerAnonymousSeattle/computer/issues/29
