### ISSUE TITLE
How will other people identify our group at the meeting place?

### ISSUE THREAD

**Issue by whatdog** [ComputerAnonymousSeattle/computer#4]

**Comment by mjgiarlo** [comment]
Jaunty hats? :tophat:

**Comment by mjgiarlo** [comment]
@whatdog: Maybe you or @diplomatica or I could print out or Sharpie up a cheesy little sign thing.

**Comment by mjgiarlo** [comment]
First person to craft a sign, feel free to close this issue!

**Comment by mjgiarlo** [comment]
No signs yet?  We could make one with cocktail napkins and wear it as a hat.

**Comment by mjgiarlo** [comment]
We have a snazzy sign now!
