### ISSUE TITLE
"Register" for first meeting (10/24) here!

### ISSUE THREAD

**Issue by mjgiarlo** [ComputerAnonymousSeattle/computer#6]
This issue is so we can get a sense of who is planning to attend.  If you've already indicated you're attending via the Facebook or Google+ events, we'll track the numbers there as well.

Please leave a comment below if you are attending.

**Comment by JaimeLynSchatz** [comment]
I'm on Google Maps right now, planning my route! I'm super excited to see a chapter of CA in Seattle!

**Comment by mjgiarlo** [comment]
Great, @JaimeLynSchatz!

**Comment by JaimeLynSchatz** [comment]
I wasn't able to secure an early exit from work today - will people still be around at around 6:30?

**Comment by mjgiarlo** [comment]
I'm sure we will be, @JaimeLynSchatz, yes. :smile:

**Comment by JaimeLynSchatz** [comment]
-( I'm so sorry but I have to bail. :(  Hope to see folks at the next one!

**Comment by mjgiarlo** [comment]
No worries, @JaimeLynSchatz.
