### ISSUE TITLE
Choose location of second meeting

### ISSUE THREAD

**Issue by mjgiarlo** [ComputerAnonymousSeattle/computer#7]
Aaand go!

**Comment by mjgiarlo** [comment]
Let's come up with 3-5 places, @diplomatica @whatdog, and then hold a vote?

**Comment by mjgiarlo** [comment]
After the vote, create a new GitHub issue for registration.

**Comment by diplomatica** [comment]
Latona Pub should be one of the options. Maybe Naked City, too?

On Fri, Oct 25, 2013 at 4:35 PM, Michael J. Giarlo <notifications@github.com

**Comment by mjgiarlo** [comment]
Thanks, @diplomatica!

Adding what I remember from Outlander, that means we've got 74th St. Alehouse, Pies & Pints, Latona Pub, and Naked City.  Were there any others?  Should we include a place south of the cut for the vote?

Any to add, @whatdog?

**Comment by diplomatica** [comment]
How about Neighbor Lady for south of the ship canal? It's right on the 48
line (UW bus line).

On Sun, Oct 27, 2013 at 2:04 PM, Michael J. Giarlo <notifications@github.com

**Comment by mjgiarlo** [comment]
Cool by me. Thoughts, @whatdog?

**Comment by whatdog** [comment]
Neighbor Lady looks great. It has a vegetarian poutine!

**Comment by mjgiarlo** [comment]
OK, we have our five then!  Would someone like to whip up a survey/poll for the five locations, and I'll volunteer to distribute it via the usual channels?

**Comment by diplomatica** [comment]
Here you go, http://www.doodle.com/vckwwk4z683krz8k

On Mon, Oct 28, 2013 at 5:18 PM, Michael J. Giarlo <notifications@github.com

**Comment by diplomatica** [comment]
Let me know if I didn't do it right. First time creating doodle poll for
locations, not dates.

**Comment by mjgiarlo** [comment]
Looks good, @diplomatica!  I'll send it out today.  Thanks.

**Comment by mjgiarlo** [comment]
Distributed.  Closing the poll on November 11th, and I'll update our events and broadcast announcements when the vote is closed.

**Comment by mjgiarlo** [comment]
You may be interested too, @JaimeLynSchatz

**Comment by JaimeLynSchatz** [comment]
:D I'm looking into where they all are. (I'm a bit of a Dorothy when it comes to Seattle - I didn't grow up around here so I'm still learning the names of neighborhoods. Most of my jaunts to Seattle are to Seattle Center ;) ) I swear I'll vote before the deadline! :D

**Comment by mjgiarlo** [comment]
OK, Pies & Pints (in the Roosevelt neighborhood) will be the site of our second meeting.  Sending out updates to our website, Twitter, the Facebook event, and the G+ event. Thanks, all.
